# Generated by Django 5.1.3 on 2025-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
