# Generated by Django 5.1.3 on 2025-11-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_is_premium_userprofile_premium_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
