"""
Django settings for trivia_spirit project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from urllib.parse import urlparse
from pathlib import Path
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="").split(",")


# CSRF trusted domains
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'storages',
    # New modular apps
    'authentication',
    'content',
    'gameplay',
    'payments',
]


# Static served locally

STATIC_URL = 'static/'
CLOUDFLARE_R2_BUCKET=config("CLOUDFLARE_R2_BUCKET")
CLOUDFLARE_R2_ACCESS_KEY=config("CLOUDFLARE_R2_ACCESS_KEY")
CLOUDFLARE_R2_SECRET_KEY=config("CLOUDFLARE_R2_SECRET_KEY")
CLOUDFLARE_R2_BUCKET_ENDPOINT=config("CLOUDFLARE_R2_BUCKET_ENDPOINT")

CLOUDFLARE_R2_CONFIG_OPTIONS ={
"bucket_name": CLOUDFLARE_R2_BUCKET,
"access_key": CLOUDFLARE_R2_ACCESS_KEY,
"secret_key": CLOUDFLARE_R2_SECRET_KEY,
"endpoint_url": CLOUDFLARE_R2_BUCKET_ENDPOINT,
"default_acl": "public-read", # private"
"signature_version": "s3v4",
}

STORAGES = {
"default": {
"BACKEND": "helpers.cloudflare.storages.MediaFileStorage", # django-stor
"OPTIONS": CLOUDFLARE_R2_CONFIG_OPTIONS,
},
"staticfiles": {
"BACKEND": "helpers.cloudflare.storages.StaticFileStorage",
"OPTIONS": CLOUDFLARE_R2_CONFIG_OPTIONS,
},
}
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'middleware.logging_middleware.RequestLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trivia_spirit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trivia_spirit.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(
        config('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
        conn_max_age=config('CONN_MAX_AGE', cast=int, default=600),  # 10 minutes default, configurable per env
        conn_health_checks=True,  # Django 4.1+ - validates connections before reuse
    )
}

# Email configuration - using ZeptoMail (Zoho transactional email service)
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend' if DEBUG else 'utils.zeptomail_backend.ZeptoMailBackend'
)
ZEPTOMAIL_API_KEY = config('ZEPTOMAIL_API_KEY', default='')
ZEPTOMAIL_API_ENDPOINT = config('ZEPTOMAIL_API_ENDPOINT', default='https://api.zeptomail.eu/')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='support@triviaspirit.com')

# FRONTEND URL - configurable per environment
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# Lemon Squeezy Configuration
LEMONSQUEEZY_API_KEY = config('LEMONSQUEEZY_API_KEY', default='')
LEMONSQUEEZY_STORE_ID = config('LEMONSQUEEZY_STORE_ID', default='')
LEMONSQUEEZY_WEBHOOK_SECRET = config('LEMONSQUEEZY_WEBHOOK_SECRET', default='')
LEMONSQUEEZY_VARIANT_ID = config('LEMONSQUEEZY_VARIANT_ID', default='')  # Product variant ID for premium plan

# Google OAuth Configuration
GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID', default='')  # Get from Google Cloud Console




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
# MEDIA_URL: URL path where uploaded files are served from
# MEDIA_ROOT: Local filesystem path where uploaded files are stored (when not using cloud storage)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'category_selection'
LOGOUT_REDIRECT_URL = 'home'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
     # 🔥 Enable throttling
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
      # 🔥 Rate limits
    "DEFAULT_THROTTLE_RATES": {
        "anon": "50/min",   # 50 requests per minute for non-auth users
        "user": "200/min",  # 200 requests per minute per authenticated user
    },

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# Caching (In-Memory)
# Using locmem cache for development. For production, configure Redis properly.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'brainigo-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        },
        'KEY_PREFIX': 'brainigo',
        'TIMEOUT': 300,  # 5 minutes default
    }
}

# Redis configuration (commented out due to version compatibility issues)
# To use Redis, ensure compatible versions of redis-py and django-redis
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'KEY_PREFIX': 'brainigo',
#         'TIMEOUT': 300,
#     }
# }

# CORS settings for React frontend
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default="").split(",")

CORS_ALLOW_CREDENTIALS = True

# Note: Image optimization is now synchronous (happens during upload)
# No Celery or background tasks needed!

# Print storage backend info
# --- Force Cloudflare R2 as the default storage backend safely ---
# ==== LOGGING CONFIGURATION ====
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'json' if not DEBUG else 'verbose',
        },
        'console_debug': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['require_debug_true'],
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
        },
    },
    'loggers': {
        # Django core loggers
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce Django noise
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce server noise
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console_debug'],  # Only in DEBUG mode
            'level':  'WARNING',
            'propagate': False,
        },
        # Third-party library loggers
        'urllib3': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce HTTP noise
            'propagate': False,
        },
        'boto3': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce AWS SDK noise
            'propagate': False,
        },
        'botocore': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        's3transfer': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Application loggers (your code)
        'authentication': {
            'handlers': ['console'],
            'level': 'INFO',  # INFO for app modules
            'propagate': False,
        },
        'content': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'gameplay': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'payments': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'middleware': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Root logger (catches everything else)
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# ==== PRODUCTION SECURITY ====
if not DEBUG:
    # Cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HTTPS redirects
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Security headers
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = "same-origin"

