# Generated by Django 5.1.3 on 2025-10-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Collection name (e.g., "Anime & Manga")', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locked', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, help_text='Category image/icon', null=True, upload_to='categories/')),
                ('description', models.TextField(blank=True, help_text='Optional description for the category')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='content.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_ar', models.TextField(blank=True)),
                ('answer', models.CharField(max_length=200)),
                ('answer_ar', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional image for the question', null=True, upload_to='questions/')),
                ('answer_image', models.ImageField(blank=True, help_text='Optional image for the answer', null=True, upload_to='answers/')),
                ('difficulty', models.CharField(choices=[('200', '200 نقطة'), ('400', '400 نقطة'), ('600', '600 نقطة')], default='200', max_length=20)),
                ('points', models.IntegerField(default=200, help_text='Points awarded for correct answer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.category')),
            ],
        ),
    ]
