# Generated by Django 5.1.3 on 2025-10-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_savedcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
