# Generated by Django 5.1.3 on 2025-10-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_question_choice_2_question_choice_3_and_more'),
    ]

    operations = [
        # Cropping field was never actually added to production, so nothing to remove
    ]
