# Generated by Django 5.1.3 on 2025-11-01 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_question_points_question_answer_image_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_custom', 'is_approved', 'privacy'], name='content_cat_is_cust_cbfbc7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_by', 'created_at'], name='content_cat_created_751dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_custom', 'privacy'], name='content_cat_is_cust_79c24a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'difficulty'], name='content_que_categor_254354_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcategory',
            index=models.Index(fields=['user', 'category'], name='content_sav_user_id_337518_idx'),
        ),
    ]
