# Generated by Django 5.1.3 on 2025-11-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_categorylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='True = category is hidden from users (but not deleted)'),
        ),
    ]
