# Generated by Django 5.1.3 on 2025-11-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_category_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='random_key',
            field=models.FloatField(db_index=True, default=0.5, help_text='Pre-shuffled order key for fast random queries'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'random_key'], name='content_que_categor_522432_idx'),
        ),
    ]
