# Generated by Django 5.1.3 on 2025-11-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_add_random_key_to_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='questions/'),
        ),
    ]
