# Generated by Django 5.1.3 on 2025-10-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playedquestion',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='playedquestion',
            name='team',
        ),
    ]
