# Generated by Django 5.1.3 on 2025-11-07 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_category_is_hidden'),
        ('gameplay', '0002_remove_playedquestion_correct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date_played']},
        ),
        migrations.AlterField(
            model_name='game',
            name='date_played',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player', '-date_played'], name='gameplay_ga_player__aa3270_idx'),
        ),
    ]
