# Generated by Django 5.1.3 on 2025-11-07 18:35

from django.db import migrations, models


def migrate_team_data_to_json(apps, schema_editor):
    """
    Copy all Team records into the Game.teams JSONField before deleting Team model.
    """
    Game = apps.get_model('gameplay', 'Game')
    Team = apps.get_model('gameplay', 'Team')
    
    # For each game, collect its teams and store as JSON
    for game in Game.objects.all():
        teams_data = []
        for idx, team in enumerate(Team.objects.filter(game=game).order_by('id')):
            teams_data.append({
                'id': idx + 1,  # Use index as ID for frontend compatibility
                'name': team.name,
                'avatar': team.avatar,
            })
        if teams_data:  # Only save if there are teams
            game.teams = teams_data
            game.save()
    
    print(f"✓ Migrated {Game.objects.count()} games with team data to JSON")


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_alter_game_options_alter_game_date_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.JSONField(default=list, help_text='List of teams: [{"name": "...", "avatar": "..."}]'),
        ),
        # Migrate data BEFORE deleting the Team model
        migrations.RunPython(migrate_team_data_to_json, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
