# Generated by Django 5.1.3 on 2025-11-07 18:36

from django.db import migrations


def migrate_team_data_to_json(apps, schema_editor):
    """
    Safety no-op: 0004 already migrated data and deleted Team.
    If Team still exists (e.g., during partial rollback), migrate; otherwise, skip.
    """
    Game = apps.get_model('gameplay', 'Game')
    try:
        Team = apps.get_model('gameplay', 'Team')
    except LookupError:
        # Team model no longer exists; nothing to do.
        return

    for game in Game.objects.all():
        teams_data = []
        for idx, team in enumerate(Team.objects.filter(game=game).order_by('id')):
            teams_data.append({
                'id': idx + 1,
                'name': team.name,
                'avatar': team.avatar,
            })
        if teams_data:
            game.teams = teams_data
            game.save(update_fields=["teams"]) 
    
    # Print omitted in migrations to avoid noise


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_game_teams_delete_team'),
    ]

    operations = [
        migrations.RunPython(migrate_team_data_to_json, reverse_code=migrations.RunPython.noop),
    ]
