# Generated by Django 5.1.3 on 2025-11-24 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Lemon Squeezy order ID', max_length=255, unique=True)),
                ('customer_id', models.CharField(blank=True, help_text='Lemon Squeezy customer ID', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('variant_id', models.CharField(help_text='Product variant purchased', max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_data', models.JSONField(blank=True, help_text='Raw webhook payload', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='payments_pa_created_3147e3_idx'), models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx'), models.Index(fields=['order_id'], name='payments_pa_order_i_1d1c93_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(help_text='Lemon Squeezy subscription ID', max_length=255, unique=True)),
                ('customer_id', models.CharField(help_text='Lemon Squeezy customer ID', max_length=255)),
                ('order_id', models.CharField(blank=True, help_text='Initial order ID', max_length=255)),
                ('variant_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('on_trial', 'On Trial'), ('active', 'Active'), ('paused', 'Paused'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('renews_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_su_user_id_058311_idx'), models.Index(fields=['subscription_id'], name='payments_su_subscri_8b825c_idx')],
            },
        ),
    ]
